#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'
require 'rbconfig'

PROJECT_DIR = File.expand_path('..', __dir__)
LOADER_NAME = 'su_takeoff_dev_loader.rb'

def host_os
  RbConfig::CONFIG['host_os']
end

def macos_plugins_dir(version)
  File.join(
    Dir.home,
    'Library',
    'Application Support',
    "SketchUp #{version}",
    'SketchUp',
    'Plugins'
  )
end

def windows_plugins_dir(version)
  appdata = ENV['APPDATA'] || File.join(Dir.home, 'AppData', 'Roaming')
  File.join(appdata, 'SketchUp', "SketchUp #{version}", 'SketchUp', 'Plugins')
end

def existing_macos_plugins_dirs
  Dir.glob(File.join(Dir.home, 'Library', 'Application Support', 'SketchUp *', 'SketchUp', 'Plugins')).sort
end

def target_plugins_dir
  version = ARGV[0] || ENV['SKETCHUP_VERSION']
  if host_os =~ /darwin/i
    return macos_plugins_dir(version) if version

    existing_macos_plugins_dirs.last || macos_plugins_dir('2023')
  elsif host_os =~ /mswin|mingw|cygwin/i
    windows_plugins_dir(version || '2023')
  else
    abort "Unsupported OS: #{host_os}"
  end
end

plugins_dir = target_plugins_dir
loader_path = File.join(plugins_dir, LOADER_NAME)

FileUtils.mkdir_p(plugins_dir)
File.write(loader_path, <<~RUBY)
  # frozen_string_literal: true
  # Auto-generated by su-takeoff/tools/install_dev_loader.rb
  # This loader points SketchUp at the live source tree for fast development.

  $su_takeoff_dev_mode = true
  $su_takeoff_project_dir = #{PROJECT_DIR.inspect}

  unless File.exist?(File.join($su_takeoff_project_dir, 'su_takeoff.rb'))
    raise "SU Takeoff source tree not found: " + $su_takeoff_project_dir.to_s
  end

  load File.join($su_takeoff_project_dir, 'su_takeoff.rb')
RUBY

puts "Dev loader written: #{loader_path}"
puts "Source tree: #{PROJECT_DIR}"

installed_loader = File.join(plugins_dir, 'su_takeoff_loader.rb')
if File.exist?(installed_loader)
  warn "Notice: found packaged loader: #{installed_loader}"
  warn "In SketchUp, use Plugins -> SU Takeoff Dev. Disable the packaged extension if duplicate menus are confusing."
end
